/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as InsigniasRouteImport } from './routes/insignias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosCursoIdRouteImport } from './routes/cursos.$cursoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const InsigniasRoute = InsigniasRouteImport.update({
  id: '/insignias',
  path: '/insignias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosCursoIdRoute = CursosCursoIdRouteImport.update({
  id: '/cursos/$cursoId',
  path: '/cursos/$cursoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/amigos': typeof AmigosRoute
  '/insignias': typeof InsigniasRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/cursos/$cursoId': typeof CursosCursoIdRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/amigos': typeof AmigosRoute
  '/insignias': typeof InsigniasRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/cursos/$cursoId': typeof CursosCursoIdRoute
  '/cursos': typeof CursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/amigos': typeof AmigosRoute
  '/insignias': typeof InsigniasRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/cursos/$cursoId': typeof CursosCursoIdRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad'
    | '/admin'
    | '/amigos'
    | '/insignias'
    | '/perfil'
    | '/premium'
    | '/ranking'
    | '/registro'
    | '/cursos/$cursoId'
    | '/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividad'
    | '/admin'
    | '/amigos'
    | '/insignias'
    | '/perfil'
    | '/premium'
    | '/ranking'
    | '/registro'
    | '/cursos/$cursoId'
    | '/cursos'
  id:
    | '__root__'
    | '/'
    | '/actividad'
    | '/admin'
    | '/amigos'
    | '/insignias'
    | '/perfil'
    | '/premium'
    | '/ranking'
    | '/registro'
    | '/cursos/$cursoId'
    | '/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  AdminRoute: typeof AdminRoute
  AmigosRoute: typeof AmigosRoute
  InsigniasRoute: typeof InsigniasRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  RankingRoute: typeof RankingRoute
  RegistroRoute: typeof RegistroRoute
  CursosCursoIdRoute: typeof CursosCursoIdRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insignias': {
      id: '/insignias'
      path: '/insignias'
      fullPath: '/insignias'
      preLoaderRoute: typeof InsigniasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$cursoId': {
      id: '/cursos/$cursoId'
      path: '/cursos/$cursoId'
      fullPath: '/cursos/$cursoId'
      preLoaderRoute: typeof CursosCursoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  AdminRoute: AdminRoute,
  AmigosRoute: AmigosRoute,
  InsigniasRoute: InsigniasRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  RankingRoute: RankingRoute,
  RegistroRoute: RegistroRoute,
  CursosCursoIdRoute: CursosCursoIdRoute,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
